package com.walking.backend.domain.model;

public enum ActivityType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_MOVED,
    TASK_COMPLETED,
    TASK_REOPENED,
    TASK_LABEL_ADDED,
    TASK_LABEL_DELETED,

    SECTION_CREATED,
    SECTION_UPDATED,
    SECTION_DELETED,

    LABEL_CREATED,
    LABEL_UPDATED,
    LABEL_DELETED,

    BOARD_CREATED,
    BOARD_UPDATED,
    BOARD_DELETED,

    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    MEMBER_LEAVED
}
