server:
  port: 0
spring:
  application:
    name: task-tracker-scheduler
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/task_tracker_scheduler_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: scheduler-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.walking.backend.domain.dto.kafka.UserActivityEvent
        spring.json.type.mapping: UserActivityEvent:com.walking.scheduler.domain.dto.UserActivityEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      compression-type: lz4
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 10
        batch.size: 32768
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        retry.backoff.ms: 500
        spring.json:
          add.type.headers: true
          type.mapping: MessageDto:com.walking.scheduler.domain.dto.MessageDto
app:
  kafka:
    topics:
      email-sending: email_sending_tasks
      user_activity: user_activities
  scheduler:
    cron: '0 0 23 * * *'
    batch-size: 100